DjangoPytania/mysite/sw_site/questions/urls.py
from django.urls import path

app_name = 'questions'

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('practise/', views.practise, name='practise'),
    path('practise/<pk>/', views.single_question_view, name='single_question'),
    path('play/', views.PlayView.as_view(), name='play'),
]

DjangoPytania/mysite/sw_site/sw_site/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('questions/', include('questions.urls')),
    path('recruiter_game/', include('recruiter_game.urls')),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoPytania/mysite/sw_site/questions/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    number_of_question = models.PositiveIntegerField(primary_key=True, unique=True)
    question_content = models.TextField(max_length=1000)
    answer_a = models.TextField(max_length=250)
    answer_b = models.TextField(max_length=250)
    answer_c = models.TextField(max_length=250)
    a_is_correct = models.BooleanField()
    b_is_correct = models.BooleanField()
    c_is_correct = models.BooleanField()
    question_notes = models.TextField(max_length=1000)


    def check_answers(self, user_answers):
        proper_answers = [self.a_is_correct, self.b_is_correct, self.c_is_correct]
        return proper_answers == user_answers

    def __str__(self):
        return f"Pytanie nr {self.number_of_question}"

    # def create_question(self, question_listed):
    #     self.number_of_question = question_listed[0]
    #     self.question_content = question_listed[1]
    #     self.answer_a = question_listed[2]
    #     self.answer_b = question_listed[3]
    #     self.answer_c = question_listed[4]
    #     self.a_is_correct = "a" in question_listed[5]
    #     self.b_is_correct = "b" in question_listed[5]
    #     self.c_is_correct = "c" in question_listed[5]
    #     self.question_notes = question_listed[6]


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    number_of_question = models.PositiveIntegerField()
    answer_a = models.BooleanField(blank=True)
    answer_b = models.BooleanField(blank=True)
    answer_c = models.BooleanField(blank=True) 
    answer_is_proper = models.BooleanField()

DjangoPytania/mysite/sw_site/questions/forms.py
from django import forms 
from .models import Answer


class AnswerForm(forms.Form):

    answer_a = forms.BooleanField()    
    answer_b = forms.BooleanField() 
    answer_c = forms.BooleanField() 
         

DjangoPytania/mysite/sw_site/questions/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Question, Answer
from django.views.generic import ListView, TemplateView, View 
from django.views.generic.edit import FormView
# Create your views here.
from .forms import AnswerForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse


def home(response):
    return render(response, 'home.html', {"title": "Tytuł"})


def practise(response):
    all_questions = Question.objects.all()
    context = {
        "all_questions": all_questions
    }

    return render(response, 'practise.html', context)

def single_question_view(response, pk):

    try:
        question = Question.objects.get(pk=pk)
    except Question.DoesNotExist:
        raise Http404("Question not exist")


    return render(response, 'single_question.html', {'question': question})


import random  


class PlayView(ListView):
    template_name = 'play.html'



    def get(self, request):
        single_question = random.choice(Question.objects.all())
        try:
            points = request.session['points']
        except KeyError:
            points = None
        context = {
            'single_question': single_question,
            'points': points
        }
        return render(request, self.template_name, context)


    @method_decorator(login_required)
    def post(self, request):
    
        question_number = request.POST.get("question_number")
        answer = Answer()
        
        answer.number_of_question = int(question_number)
        
        answer.answer_a = "A" == request.POST.get("answera")
        answer.answer_b = "B" == request.POST.get("answerb")
        answer.answer_c = "C" == request.POST.get("answerc")
        user_answers = [answer.answer_a, answer.answer_b, answer.answer_c]

        single_question = Question.objects.get(pk=question_number)
        answer.answer_is_proper = single_question.check_answers(user_answers)

        answer.save()
        print(request.user)
        if answer:
            print(answer.answer_is_proper)
            print("Poprawna odpowiedź to A")
      
        request.session['points'] = 10
    
        return redirect(request.path)




    # def get(self, request):
    #     all_questions = Question.objects.all()
    #     random_question = random.randint(1, len(all_questions))
    #     context = {
    #                 "all_questions": all_questions,
    #                 "random_number": random_question
    #             }
    #     return render(request, 'play.html', context)    

    # def post(self, request):
    #     answer = request.POST.get("answer")
    #     self.object = self.get_object()
    #     print(answer)
    #     print(self.object)


# def play_view(request):
#     all_questions = Question.objects.all()
#     random_question = random.randint(1, len(all_questions))
#     correct_answers = all_questions[random_question - 1].give_answers()

    
#     context = {
#             "all_questions": all_questions,
#             "random_number": random_question,
#             "correct_answers": correct_answers
#         }

#     if request.method == "GET":
#         return render(request, 'play.html', context)
    

#     if request.method == "POST":
#         answer = request.POST.get("answer")
#         correct_ans = get_object()
#         print(answer)
#         print(correct_ans)

        
#         return render(request, 'check_answer.html')
    

    


        

DjangoPytania/mysite/sw_site/questions/templates/questions/base.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" 
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" 
    crossorigin="anonymous"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'questions/style.css' %}"/>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>{% block title %}Szymon strona{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Wróć na stronę główną</a>

    </nav>  

{% block content %}
{% endblock content %}
</body>

</html>




 

DjangoPytania/mysite/sw_site/questions/templates/questions/home.html
{% extends "questions/base.html" %}
{% load static %}


{% block title %}
QUIZ
{% endblock title %}




<body>
    {% block content %}

    <div class="container">
        <div class="row align-items-start"></div>
            <div class="col">
                <a href="play"></a>
                <p>Zagraj</p>
            </div>
            <div class="col">
                <a href="practise"></a>
                Poćwicz
            </div>
        </div>
    </div>   
    {% endblock content %}
</body>

DjangoPytania/mysite/sw_site/questions/templates/questions/play.html
{% extends "questions/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% endblock title %}

{% block content %}






<div class="question-answer-form">
    <div class="question-title">Pytanie nr: {{single_question.number_of_question}}. {{single_question.question_content}}</div>
    <form method="post" >
        {% csrf_token %} 
        <div class="form-check">
            {{form|crispy}}
            A: {{single_question.answer_a}} 
            <input class="form-check-input" type="checkbox" value="A" id="A" name="answera">
            <br>
            B: {{single_question.answer_b}}
            <input class="form-check-input" type="checkbox" value="B" id="B" name="answerb">
            <br>
            C: {{single_question.answer_c}}
            <br>
            {{points}}
            <input class="form-check-input" type="checkbox" value="C" id="C" name="answerc">
            <input type="hidden" value="{{single_question.number_of_question}}" name="question_number">
            <br>
            <button type="submit" class="btn btn-info">Sprawdź</button>
        </div> 
    </form>
</div>


{% endblock content %}

DjangoPytania/mysite/sw_site/questions/templates/questions/practise.html
{% extends "questions/base.html" %}

{% block content %}
{% load static %}

{% for question in all_questions %}
    <div class="single-q">
        <a href="{% url 'questions:single_question' question.pk %}">{{question}}. {{question.question_content}}</a> 
    </div>

{% endfor %}

{% endblock content %}

DjangoPytania/mysite/sw_site/questions/templates/questions/single_question.html
{% extends "questions/base.html" %}

{% block content %}
{% load static %}
<div class="question-title">Pytanie nr: {{question.number_of_question}}. {{question.question_content}}</div>
<div class="question-answer">
    A: {{question.answer_a}}
    <br>
    B: {{question.answer_b}}
    <br>
    C: {{question.answer_c}}    
</div>


    
    

{% endblock content %}